#!/usr/bin/env python3
"""Estimate accelerometer bias and scale from six static faces.

Input CSV columns:

    face,ax,ay,az

Use the labels ``+x``, ``-x``, ``+y``, ``-y``, ``+z`` and ``-z``.  Every row
is one stationary sample.  The default ellipsoid fit estimates a full affine
matrix, which is the same form used by ``origincarpro_base``:

    a_calibrated = acc_ta @ (a_measured - acc_ba)

The simpler diagonal model is also available with ``--model diagonal``.  The
output can be copied into ``origincarpro_base.yaml`` only after checking the
residuals and validating it on the real vehicle.
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import numpy as np


FACES = ("+x", "-x", "+y", "-y", "+z", "-z")


def normalize_face(value: str) -> str:
    text = value.strip().lower().replace(" ", "")
    aliases = {
        "x+": "+x", "posx": "+x", "plusx": "+x",
        "x-": "-x", "negx": "-x", "minusx": "-x",
        "y+": "+y", "posy": "+y", "plusy": "+y",
        "y-": "-y", "negy": "-y", "minusy": "-y",
        "z+": "+z", "posz": "+z", "plusz": "+z",
        "z-": "-z", "negz": "-z", "minusz": "-z",
    }
    return aliases.get(text, text)


def load_samples(path: Path, accel_scale: float) -> dict[str, np.ndarray]:
    samples: dict[str, list[list[float]]] = defaultdict(list)
    with path.open("r", encoding="utf-8-sig", newline="") as stream:
        reader = csv.DictReader(stream)
        if not reader.fieldnames:
            raise ValueError("CSV 缺少表头")
        face_column = "face" if "face" in reader.fieldnames else "pose"
        required = {face_column, "ax", "ay", "az"}
        if not required.issubset(reader.fieldnames):
            raise ValueError(f"CSV 必须包含列: {', '.join(sorted(required))}")
        for row in reader:
            face = normalize_face(row[face_column])
            if face not in FACES:
                raise ValueError(f"未知面标签 {row[face_column]!r}，应使用 +x/-x/+y/-y/+z/-z")
            samples[face].append([
                float(row[axis]) / accel_scale for axis in ("ax", "ay", "az")
            ])

    missing = [face for face in FACES if not samples[face]]
    if missing:
        raise ValueError(f"缺少六面数据: {', '.join(missing)}")
    return {face: np.asarray(values, dtype=float) for face, values in samples.items()}


def fit_diagonal(means: dict[str, np.ndarray], gravity: float) -> tuple[np.ndarray, np.ndarray]:
    bias = np.zeros(3, dtype=float)
    scale = np.zeros(3, dtype=float)
    for index, axis in enumerate(("x", "y", "z")):
        positive = means[f"+{axis}"][index]
        negative = means[f"-{axis}"][index]
        span = positive - negative
        if abs(span) < 1.0e-12:
            raise ValueError(f"{axis} 轴正负面读数几乎相同，无法估计尺度")
        bias[index] = 0.5 * (positive + negative)
        scale[index] = 2.0 * gravity / span
    return bias, np.diag(scale)


def fit_ellipsoid(samples: dict[str, np.ndarray], gravity: float) -> tuple[np.ndarray, np.ndarray]:
    points = np.vstack(list(samples.values()))
    if len(points) < 10:
        raise ValueError("椭球拟合至少需要 10 个样本，建议每个面采集几十秒")
    x, y, z = points[:, 0], points[:, 1], points[:, 2]
    design = np.column_stack([
        x * x, y * y, z * z,
        2.0 * x * y, 2.0 * x * z, 2.0 * y * z,
        2.0 * x, 2.0 * y, 2.0 * z,
        np.ones_like(x),
    ])
    _, _, vh = np.linalg.svd(design, full_matrices=False)
    params = vh[-1, :]
    matrix = np.array([
        [params[0], params[3], params[4]],
        [params[3], params[1], params[5]],
        [params[4], params[5], params[2]],
    ])
    linear = params[6:9]
    constant = float(params[9])
    if np.trace(matrix) < 0.0:
        matrix = -matrix
        linear = -linear
        constant = -constant
    if np.min(np.linalg.eigvalsh(matrix)) <= 0.0:
        raise ValueError("椭球拟合得到的二次型不是正定矩阵，检查姿态覆盖和异常样本")

    bias = -0.5 * np.linalg.solve(matrix, linear)
    k = float(bias @ matrix @ bias - constant)
    if k <= 0.0:
        raise ValueError("椭球拟合失败：归一化常数不为正")
    shape = matrix / k
    # np.linalg.cholesky returns L with L @ L.T = shape.  The runtime uses
    # Ta.T @ Ta, so store the upper-triangular transpose.
    transform = np.linalg.cholesky(shape).T * gravity
    return bias, transform


def write_yaml(path: Path, bias: np.ndarray, transform: np.ndarray,
               means: dict[str, np.ndarray], residuals: dict[str, float],
               gravity: float, accel_scale: float, model: str) -> None:
    with path.open("w", encoding="utf-8") as stream:
        stream.write("# Generated by calibrate_imu_six_face.py\n")
        stream.write("# acc_ta @ (acc - acc_ba), in the post-scale input units.\n")
        stream.write("acc_ba: [%s]\n" % ", ".join(f"{v:.10g}" for v in bias))
        stream.write("acc_ta: [%s]\n" % ", ".join(f"{v:.10g}" for v in transform.reshape(-1)))
        stream.write(f"gravity: {gravity:.10g}\n")
        stream.write(f"input_accel_scale: {accel_scale:.10g}\n")
        stream.write(f"model: {model}\n")
        stream.write("face_means:\n")
        for face in FACES:
            stream.write("  %s: [%s]\n" % (face, ", ".join(f"{v:.10g}" for v in means[face])))
        stream.write("face_norm_error:\n")
        for face in FACES:
            stream.write(f"  {face}: {residuals[face]:.10g}\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="六面静态样本 CSV")
    parser.add_argument("--output", type=Path, required=True, help="输出 YAML")
    parser.add_argument("--model", choices=("ellipsoid", "diagonal"), default="ellipsoid",
                        help="拟合完整矩阵或仅拟合轴向偏置/尺度")
    parser.add_argument("--gravity", type=float, default=9.80665,
                        help="重力加速度，默认 9.80665，与输入单位一致")
    parser.add_argument("--accel-scale", type=float, default=1.0,
                        help="输入值除以该尺度后再拟合；原始 LSB 可传 16384")
    args = parser.parse_args()

    if args.accel_scale <= 0.0:
        raise ValueError("--accel-scale 必须大于 0")
    samples = load_samples(args.input, args.accel_scale)
    means = {face: values.mean(axis=0) for face, values in samples.items()}
    if args.model == "ellipsoid":
        bias, transform = fit_ellipsoid(samples, args.gravity)
    else:
        bias, transform = fit_diagonal(means, args.gravity)

    residuals: dict[str, float] = {}
    for face, mean in means.items():
        corrected = transform @ (mean - bias)
        residuals[face] = float(np.linalg.norm(corrected) - args.gravity)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    write_yaml(args.output, bias, transform, means, residuals, args.gravity,
               args.accel_scale, args.model)
    print("acc_ba =", bias.tolist())
    print("acc_ta =\n", transform)
    print("最大六面重力模长误差 =", max(abs(value) for value in residuals.values()))
    print("结果已写入", args.output)


if __name__ == "__main__":
    main()
