#!/usr/bin/env python3
"""Estimate stationary gyroscope bias from a CSV file.

The CSV must contain ``gx``, ``gy`` and ``gz`` in the same units used by the
ROS IMU message, normally rad/s.  Keep the IMU completely still while
collecting the samples.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="静止 IMU CSV")
    parser.add_argument("--output", type=Path, required=True, help="输出 YAML")
    args = parser.parse_args()

    frame = pd.read_csv(args.input)
    columns = ["gx", "gy", "gz"]
    missing = [column for column in columns if column not in frame]
    if missing:
        raise ValueError(f"CSV 缺少列: {', '.join(missing)}")
    values = frame[columns].apply(pd.to_numeric, errors="coerce").dropna()
    if values.empty:
        raise ValueError("没有有效陀螺仪样本")

    mean = values.mean()
    std = values.std(ddof=1)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as stream:
        stream.write("# Generated by estimate_gyro_bias.py\n")
        stream.write("gyro_bias: [%s]\n" % ", ".join(f"{mean[name]:.10g}" for name in columns))
        stream.write("gyro_std: [%s]\n" % ", ".join(f"{std[name]:.10g}" for name in columns))
        stream.write(f"sample_count: {len(values)}\n")

    print("gyro_bias =", [float(mean[name]) for name in columns])
    print("sample_count =", len(values))
    print("结果已写入", args.output)


if __name__ == "__main__":
    main()
